#!/usr/bin/env bash
# Generate TEST_REPORT.md from test-state.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORTS_DIR="$(cd "$SCRIPT_DIR/../reports" && pwd)"

source "$SCRIPT_DIR/lib/test-state.sh"

target_url=$(state_get '.pipeline.targetUrl')
started_at=$(state_get '.pipeline.startedAt')
completed_at=$(state_get '.pipeline.completedAt')
total_units=$(state_get '.pipeline.totalUnits')
completed_units=$(state_get '.pipeline.completedUnits')
failed_units=$(state_get '.pipeline.failedUnits')

# Determine report filename based on target
if echo "$target_url" | grep -q "redwhitereno\|leadquoteenginev2"; then
  report_file="$REPORTS_DIR/TEST_REPORT-redwhitereno.md"
else
  report_file="$REPORTS_DIR/TEST_REPORT-demo.md"
fi

cat > "$report_file" <<EOF
# ConversionOS Test Report

**Target:** $target_url
**Started:** $started_at
**Completed:** $completed_at
**Units:** $completed_units / $total_units completed ($failed_units failed)

---

## Summary

| Unit | Name | Status | Tests | Passed | Failed | Skipped | Duration |
|------|------|--------|-------|--------|--------|---------|----------|
EOF

# Add each unit row
for unit_id in "T-01" "T-02" "T-03" "T-04" "T-05" "T-06" "T-07" "T-08" "T-09" "T-10" "T-11" "T-12" "T-13" "T-14" "T-15" "T-16" "T-17" "T-18"; do
  name=$(state_get ".units[\"$unit_id\"].name")
  status=$(state_get ".units[\"$unit_id\"].status")
  tests=$(state_get ".units[\"$unit_id\"].tests")
  passed=$(state_get ".units[\"$unit_id\"].passed")
  failed=$(state_get ".units[\"$unit_id\"].failed")
  skipped=$(state_get ".units[\"$unit_id\"].skipped")
  duration=$(state_get ".units[\"$unit_id\"].duration")

  status_emoji=""
  case "$status" in
    complete) status_emoji="✅" ;;
    failed)   status_emoji="❌" ;;
    blocked)  status_emoji="🚫" ;;
    running)  status_emoji="🔄" ;;
    skipped)  status_emoji="⏭️" ;;
    *)        status_emoji="⏳" ;;
  esac

  echo "| $unit_id | $name | $status_emoji $status | $tests | $passed | $failed | $skipped | $duration |" >> "$report_file"
done

cat >> "$report_file" <<EOF

---

## Total Test Count

$(jq -r '
  [.units | to_entries[] | .value] |
  {
    total_tests: (map(.tests) | add),
    total_passed: (map(.passed) | add),
    total_failed: (map(.failed) | add),
    total_skipped: (map(.skipped) | add)
  } |
  "- **Total tests:** \(.total_tests)\n- **Passed:** \(.total_passed)\n- **Failed:** \(.total_failed)\n- **Skipped:** \(.total_skipped)"
' "$STATE_FILE")

---

*Generated by ConversionOS Autonomous Testing Pipeline*
*$(date -u +"%Y-%m-%d %H:%M:%S UTC")*
EOF

echo "Report generated: $report_file"
